// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4izf9vTsMyc0GXsHJ_xp1QmqrtvcIacM',
    appId: '1:141951058720:web:3a5aa186fd3155dbdf4d45',
    messagingSenderId: '141951058720',
    projectId: 'slime-fall',
    authDomain: 'slime-fall.firebaseapp.com',
    storageBucket: 'slime-fall.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuDMpvpSAK36Ek3043x7479UQ6L8eBMfw',
    appId: '1:141951058720:android:3b4a00eda0fb1c2bdf4d45',
    messagingSenderId: '141951058720',
    projectId: 'slime-fall',
    storageBucket: 'slime-fall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr72W52haZSfSntR00yqgFGgbCsZL08LA',
    appId: '1:141951058720:ios:6605f8cea747c063df4d45',
    messagingSenderId: '141951058720',
    projectId: 'slime-fall',
    storageBucket: 'slime-fall.appspot.com',
    iosBundleId: 'com.example.slimeFall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr72W52haZSfSntR00yqgFGgbCsZL08LA',
    appId: '1:141951058720:ios:6605f8cea747c063df4d45',
    messagingSenderId: '141951058720',
    projectId: 'slime-fall',
    storageBucket: 'slime-fall.appspot.com',
    iosBundleId: 'com.example.slimeFall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4izf9vTsMyc0GXsHJ_xp1QmqrtvcIacM',
    appId: '1:141951058720:web:3a072f3af4f122ffdf4d45',
    messagingSenderId: '141951058720',
    projectId: 'slime-fall',
    authDomain: 'slime-fall.firebaseapp.com',
    storageBucket: 'slime-fall.appspot.com',
  );
}
